### ISSUE TITLE
Set duration

### ISSUE THREAD

**Issue by benjick** [jimmycodesocial/simple-oauth2-reddit#1]
Hey! Thanks for the library

How can I set duration to `permanent`?

**Comment by albertomr86** [comment]
Hi!

You can provide custom [options](https://github.com/jimmycodesocial/simple-oauth2-reddit#options) for the [authorization](https://github.com/reddit-archive/reddit/wiki/OAuth2#authorization). The one you're looking for is **authorizeOptions**.

Try this...

```js
const reddit = simpleOAuth2Reddit.create({
  clientId: process.env.REDDIT_APP_ID,
  clientSecret: process.env.REDDIT_APP_SECRET,
  callbackURL: 'http://localhost:3000/auth/reddit/callback',
  state: 'random-unique-string',
  authorizeOptions: {
    duration: 'permanent'
  },
});
```
Curious?: Take a look at https://github.com/jimmycodesocial/simple-oauth2-reddit/blob/master/src/index.js#L82-L91

Let me know if worked for you.
Thanks.

**Comment by benjick** [comment]
Thank you!
